name: Build Pipeline

on: 
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

permissions: 
    id-token: write
    contents: read
    pull-requests: write

jobs: 
    build:
        name: Terraform-Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Azure Login
              uses: azure/login@v3
              with:
                client-id: ${{secrets.ARM_CLIENT_ID}}
                tenant-id: ${{secrets.ARM_TENANT_ID}}
                subscription-id: ${{secrets.ARM_SUBSCRIPTION_ID}}

             
            - name: Setup terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.15.8

            - name: Verifying installation
              run : terraform -version
              shell: bash

            - name: Installing Python
              uses: actions/setup-python@v5
              with: 
                python-version: 3.13

            - name: Verifying py installation
              run: python --version

            - name: Installing Checkov
              run: python -m  pip install checkov

            - name: Verifying checkov installation
              run: checkov --version

            - name: Checkov Checks 
              run: checkov -d . --soft-fail

            - name: Terraform Formatting
              run: terraform fmt -check

            - name: Terraform Initialization
              run: terraform init

            - name: Terraform validate
              run: terraform validate

            - name: Terraform plan stage
              run: terraform plan -out main.tfplan

            - name: Terraform artifact stage
              uses: actions/upload-artifact@v4
              with: 
                name: Terraform-plan
                path: tfplan


            # - name: Docker login
            #   uses: docker/login-action@v4
            #   with: 
            #         username: ${{secrets.DOCKERHUB_USERNAME}}
            #         password: ${{secrets.DOCKERHUB_TOKEN}}
            
            # # - name: Setup QEMU
            # #   uses: docker/setup-qemu-action@4

            # - name: Setup docker build
            #   uses: docker/setup-buildx-action@v4

            # - name: Build and Push
            #   uses: docker/build-push-action@v7
            #   with: 
            #         context: .
            #         push: true
            #         tags: sachinbasera27/machop_repos:latest

            #     # run: |
            #     #     docker login cred
            #     #     docker build ...
            #     #     docker 

# https://docs.github.com/en/actions/tutorials/store-and-share-data
# https://github.com/azure-samples/terraform-github-actions/blob/main/.github/workflows/tf-plan-apply.yml
# https://github.com/Azure/login
# https://github.com/marketplace/actions/build-and-push-docker-images
