name: Deploy Pipeline

on:
    workflow_run:
        workflows: [Build Pipeline]
        types: 
            - completed
    workflow_dispatch:


permissions: 
    id-token: write
    contents: read

jobs:

    on-success:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
        - run: echo 'The triggering workflow passed'
        
    on-failure:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
        - run: echo 'The triggering workflow failed'

    deploy:
        name: Terraform-Apply
        runs-on: ubuntu-latest

        env:
            ARM_USE_OIDC: "true"    # Used to tell terraform to use OIDC 

        steps:

            - name: Checkout
              uses: actions/checkout@v2

            - name: Terraform Installation
              uses: hashicorp/setup-terraform@v4
              with:
                terraform_version: "1.15.8"

            - name: Terraform Init
              run: terraform init

            - name: Azure Login Step
              uses: azure/login@v2
              with: 
                client-id: ${{ secrets.ARM_CLIENT_ID }}
                tenant-id: ${{ secrets.ARM_TENANT_ID }}
                subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

            - name: Adding the Artifact to the runner
              uses: actions/download-artifact@v4
              with:
                name: Terraform-plan
                run-id: ${{github.event.workflow_run.id}}
                github-token: ${{github.token}}


            - name: Terraform Apply
              run: terraform apply -auto-approve tfplan


# https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#workflow_call
# https://docs.github.com/en/actions/how-tos/manage-workflow-runs/manually-run-a-workflow
# https://github.com/hashicorp/setup-terraform
